# Generated by Django 3.2.25 on 2024-03-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtype',
            name='description',
            field=models.CharField(default='This is description', max_length=250),
        ),
    ]
