# Generated by Django 3.2.25 on 2024-03-23 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chapter',
            fields=[
                ('chap_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('chap_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('q_type', models.CharField(choices=[('mcq', 'mcq'), ('fillin', 'fillin'), ('tf', 'tf')], max_length=8)),
                ('question', models.CharField(max_length=1500)),
                ('q_image', models.ImageField(blank=True, upload_to='./qimages')),
                ('choice1', models.CharField(max_length=100)),
                ('choice2', models.CharField(max_length=100)),
                ('choice3', models.CharField(max_length=100)),
                ('choice4', models.CharField(max_length=100)),
                ('topic', models.CharField(blank=True, max_length=500)),
                ('marks', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('negative', models.FloatField(choices=[(-0.33, -0.33), (0, 0), (-0.66, -0.66)])),
                ('diff_level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('VeryHard', 'VeryHard')], max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('correct_attempts', models.IntegerField(default=0)),
                ('chapter', models.ForeignKey(default='102', on_delete=django.db.models.deletion.SET_DEFAULT, to='questions.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('sub_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='solution',
            fields=[
                ('q_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='questions.question')),
                ('answer', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('topic_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=50)),
                ('sub_code', models.ForeignKey(default='102', on_delete=django.db.models.deletion.SET_DEFAULT, to='questions.chapter')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(default='101', on_delete=django.db.models.deletion.SET_DEFAULT, to='questions.subject'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='sub_code',
            field=models.ForeignKey(default='101', on_delete=django.db.models.deletion.SET_DEFAULT, to='questions.subject'),
        ),
    ]
